### ISSUE TITLE
Build failures on upload?

### ISSUE THREAD

**Issue by janschulz** [conda-forge/twine-feedstock#2]
```
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
```

**Comment by jakirkham** [comment]
As mentioned elsewhere, this is the upstream issue ( https://github.com/Anaconda-Platform/support/issues/60 ). We are tracking the problem for the org in issue ( https://github.com/conda-forge/status/issues/4 ).
