### ISSUE TITLE
Missing dependency on readme_renderer? 

### ISSUE THREAD

**Issue by anschweitzer** [conda-forge/twine-feedstock#20]
`twine` depends on `readme_renderer`, but `readme_renderer` is not in conda package dependencies. As a result `twine upload` gets an exception. 

Compare twine's setup.py to twine-feedstock's meta.yaml: 
https://github.com/pypa/twine/blob/c854b2a7b451bf13878f709900261dbcbaf59ca0/setup.py#L72
https://github.com/conda-forge/twine-feedstock/blob/7e0947f488cecc31191dd2ab6abad65977e9961b/recipe/meta.yaml#L24

These steps reproduce the exception: 
```
conda create -n tmp -y
conda activate tmp
conda install twine -c conda-forge -y
# ... and from some directory with a 'dist' directory containing a build...
twine upload --repository-url  https://some-repo dist/* 
```
(I don't think you need a real repo url to reproduce the exception. You might not even need a real dist directory present).

Exception is: 
 ```
Traceback (most recent call last):
  File "/home/schweitz/miniconda3/envs/tmp/bin/twine", line 10, in <module>
    sys.exit(main())
  File "/home/schweitz/miniconda3/envs/tmp/lib/python3.7/site-packages/twine/__main__.py", line 28, in main
    return dispatch(sys.argv[1:])
  File "/home/schweitz/miniconda3/envs/tmp/lib/python3.7/site-packages/twine/cli.py", line 75, in dispatch
    main = registered_commands[args.command].load()
  File "/home/schweitz/miniconda3/envs/tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/home/schweitz/miniconda3/envs/tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/schweitz/miniconda3/envs/tmp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'readme-renderer>=21.0' distribution was not found and is required by the application
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
...
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.12.1           py37h9745a5d_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
cryptography              2.5              py37hb7f436b_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
pip                       19.0.2                   py37_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1             hd21baee_1001    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tqdm                      4.31.1                     py_0    conda-forge
twine                     1.13.0                     py_0    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wheel                     0.33.0                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
    active environment : tmp
    active env location : /home/schweitz/miniconda3/envs/tmp
            shell level : 1
       user config file : /home/schweitz/.condarc
 populated config files : /home/schweitz/.condarc
          conda version : 4.6.4
    conda-build version : 3.17.1
         python version : 3.6.7.final.0
       base environment : /home/schweitz/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/schweitz/miniconda3/pkgs
                          /home/schweitz/.conda/pkgs
       envs directories : /home/schweitz/miniconda3/envs
                          /home/schweitz/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.4 requests/2.18.4 CPython/3.6.7 Linux/4.15.0-33-generic linuxmint/18.3 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by SylvainCorlay** [comment]
Fixed in #19.
